version: '3'

services:

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - mynet

  db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
